
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: einsteinish  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-cef59af4
         assign_public_ip: yes
      register: ec2



      
#create ec2 instance

#- name: Create a new EC2 instance
  #ec2:
    #region: "{{ ec2.region }}"
    #keypair: "{{ ec2.credentials }}"
    #instance_tags: "{{ ec2.tags }}"
    #instance_type: "{{ ec2.instance_type }}"
     #image: "{{ ec2.image }}"
     #instance_profile_name: "{{ ec2.role | default('') }}"
     #group: {{ ec2.sg }}
     #vpc_subnet_id: {{ ec2.subnet }}
     #assign_public_ip: {{ ec2.public_ip | default('no') }}
     #private_ip: {{ ec2.private_ip | default('') }}